DashboardApp/src/Entity/MainStats.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MainStatsRepository")
 */
class MainStats
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $statName;

    /**
     * @ORM\Column(type="float")
     */
    private $value;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStatName(): ?string
    {
        return $this->statName;
    }

    public function setStatName(string $statName): self
    {
        $this->statName = $statName;

        return $this;
    }

    public function getValue(): ?float
    {
        return $this->value;
    }

    public function setValue(float $value): self
    {
        $this->value = $value;

        return $this;
    }
}

DashboardApp/src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $username;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lastname;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firstname;

    /**
     * @ORM\Column(type="boolean")
     */
    private $user_type;

    /**
     * @ORM\Column(type="float")
     */
    private $mark_dev;

    /**
     * @ORM\Column(type="float")
     */
    private $mark_network;

    /**
     * @ORM\Column(type="float")
     */
    private $mark_bdd;

    /**
     * @ORM\Column(type="float")
     */
    private $mark_punctuality;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getUserType(): ?bool
    {
        return $this->user_type;
    }

    public function setUserType(bool $user_type): self
    {
        $this->user_type = $user_type;

        return $this;
    }

    public function getMarkDev(): ?float
    {
        return $this->mark_dev;
    }

    public function setMarkDev(float $mark_dev): self
    {
        $this->mark_dev = $mark_dev;

        return $this;
    }

    public function getMarkNetwork(): ?float
    {
        return $this->mark_network;
    }

    public function setMarkNetwork(float $mark_network): self
    {
        $this->mark_network = $mark_network;

        return $this;
    }

    public function getMarkBdd(): ?float
    {
        return $this->mark_bdd;
    }

    public function setMarkBdd(float $mark_bdd): self
    {
        $this->mark_bdd = $mark_bdd;

        return $this;
    }

    public function getMarkPunctuality(): ?float
    {
        return $this->mark_punctuality;
    }

    public function setMarkPunctuality(float $mark_punctuality): self
    {
        $this->mark_punctuality = $mark_punctuality;

        return $this;
    }

    public function getRoles() {
        return [
            'ROLE_USER'
        ];
    }

    /**
     * Returns the salt that was originally used to encode the password.
     *
     * This can return null if the password was not encoded using a salt.
     *
     * @return string|null The salt
     */
    public function getSalt()
    {
        // TODO: Implement getSalt() method.
    }

    /**
     * Removes sensitive data from the user.
     *
     * This is important if, at any given point, sensitive information like
     * the plain-text password is stored on this object.
     */
    public function eraseCredentials()
    {
        // TODO: Implement eraseCredentials() method.
    }
}

DashboardApp/src/Controller/DashboardController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class DashboardController extends AbstractController
{
    /**
     * @Route("/", name="dashboard")
     */
    public function index()
    {
        return $this->render('dashboard/index.html.twig', [
            'controller_name' => 'DashboardController',
        ]);
    }

    public function recover_profile()
    {
        $this->get('security.token_storage')->getToken()->getUser();
        $user->getUsername();
    }
}

DashboardApp/src/Controller/ListController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\User;

class ListController extends AbstractController
{
    public function recover_all_user()
    {
        $users = $this->getDoctrine()
            ->getManager()
            ->getRepository(User::class)
            ->findAll();

        return $users;
    }

    /**
     * @Route("/liste", name="list")
     */
    public function index()
    {
        $users = $this->recover_all_user();

        return $this->render('list/index.html.twig', [
            'controller_name' => 'ListController',
            'users' => $users
        ]);
    }
}

DashboardApp/src/Controller/ProfileController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class ProfileController extends AbstractController
{
    /**
     * @Route("/profile", name="profile")
     */
    public function index()
    {
        return $this->render('profile/index.html.twig', [
            'controller_name' => 'ProfileController',
        ]);
    }

    public function recover_profile()
    {
        $this->get('security.token_storage')->getToken()->getUser();
        $user->getUsername();
    }
}

DashboardApp/src/Controller/SecurityController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;
use Symfony\Component\Routing\Annotation\Route;

class SecurityController extends AbstractController
{
    /**
     * @Route("/login", name="login")
     */
    public function login(Request $request, AuthenticationUtils $utils)
    {
        $error = $utils->getLastAuthenticationError();
        $lastUsername = $utils->getLastUsername();

        return $this->render('security/login.html.twig', [
            'error'         => $error,
            'last_username' => $lastUsername
        ]);
    }

    /**
     * @Route("/logout", name="logout")
     */

    public function logout(){

    }
}

DashboardApp/templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <title>
            {% block title %}Welcome!{% endblock %}
        </title>
        {% block stylesheets %}
            <link rel="stylesheet" href="../assets/main.css">
            <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
            <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
        {% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
        {% block javascripts %}
            <script src="../assets/js/main.js"/>
        {% endblock %}
    </body>
</html>

DashboardApp/templates/dashboard/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Dashboard - Accueil{% endblock %}

{% block body %}

    <div class="example-wrapper">
        <nav>
            <div class="nav-elements">
                <a class="nav-item home-icon tooltip active-home" href="{{ path('dashboard') }}">
                    <i class="material-icons nav-logo ">home</i>
                    <span class="tooltiptext">Accueil</span>
                </a>

                <a class="nav-item list-icon tooltip" href="{{ path('list') }}">
                    <i class="material-icons nav-logo">list</i>
                    <span class="tooltiptext">Liste</span>
                </a>

                <a class="nav-item profil-icon tooltip" href="{{ path('profile') }}">
                    <i class="material-icons nav-logo">account_circle</i>
                    <span class="tooltiptext">Profil</span>
                </a>
            </div>
            <div class="logout-element">
                <a class="nav-item logout-icon tooltip" href="{{ path('logout') }}">
                    <i class="fas fa-sign-out-alt nav-logo"></i>
                    <span class="tooltiptext">Déconnexion</span>
                </a>
            </div>

        </nav>

        <div class="main-container">
            <h2 class="hello">Bonjour
                {{ app.user.username }}
                !</h2>
            <div class="content-container">

                <div class="top-screens">
                    <div class="marks-screen">
                        <h2 class="heading underline">
                            <!--<i class="fas fa-graduation-cap classe-logo"></i>-->
                            Statistiques générales
                        </h2>
                        <div class="work-quality">
                            <p class="title-work-quality">Qualité du travail :</p>
                            <div class="progress-circle over50 p55 quality-work">
                                <span>55%</span>
                                <div class="left-half-clipper">
                                    <div class="first50-bar"></div>
                                    <div class="value-bar"></div>
                                </div>
                            </div>
                        </div>
                        <div class="plus-minus-block">
                            <div class="plus">
                                <p>Nouveaux élèves :
                                    <em>+1</em>
                                </p>
                            </div>
                            <div class="minus">
                                <p>Elèves partis :
                                    <em>-4</em>
                                </p>
                            </div>
                        </div>
                    </div>

                    <div class="marks-screen2">
                        <h2 class="heading">
                            <!--<i class="fas fa-clock ra-logo"></i>-->
                            Retards & Absences
                        </h2>
                        <div class="ponctuality-circle">
                            <p>Ponctualité</p>
                            <div class="progress-circle over50 p90 ra-circles">
                                <span>90%</span>
                                <div class="left-half-clipper">
                                    <div class="first50-bar"></div>
                                    <div class="value-bar"></div>
                                </div>
                            </div>
                        </div>
                        <div class="absent-circle">
                            <p>Absentéisme</p>
                            <div class="progress-circle p3 ra-circles">
                                <span>3%</span>
                                <div class="left-half-clipper">
                                    <div class="first50-bar"></div>
                                    <div class="value-bar"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="bottom-screens">
                    <div class="marks-screen3">
                        <h2 class="heading">
                            Classement
                        </h2>
                        <div class="scrollview">
                            <table class="list-dashboard" onload="sortTable()">
                                <thead>
                                    <tr class="head">
                                        <th>Nom</th>
                                        <th>Prénom</th>
                                        <th>Moyenne</th>
                                    </tr>
                                </thead>

                                <tbody>
                                    {% for user in users %}
                                        <tr class="body">
                                            <td>{{ user.lastname }}</td>
                                            <td>{{ user.firstname }}</td>
                                            <td class="average">{{ (user.markDev + user.markNetwork + user.markBdd)/3 }}</td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>

                    </div>
                </div>

            </div>
        </div>
    </div>

</div>
</div>

</div>
{% endblock %}

DashboardApp/templates/list/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Dashboard | Liste des élèves{% endblock %}

{% block body %}


    <nav>
        <div class="nav-elements">
            <a class="nav-item home-icon tooltip" href="{{ path('dashboard') }}">
                <i class="material-icons nav-logo ">home</i>
                <span class="tooltiptext">Accueil</span>
            </a>

            <a class="nav-item list-icon tooltip active-list" href="{{ path('list') }}">
                <i class="material-icons nav-logo">list</i>
                <span class="tooltiptext">Liste</span>
            </a>

            <a class="nav-item profil-icon tooltip" href="{{ path('profile') }}">
                <i class="material-icons nav-logo">account_circle</i>
                <span class="tooltiptext">Profil</span>
            </a>
        </div>
        <div class="logout-element">
            <a class="nav-item logout-icon tooltip" href="{{ path('logout') }}">
                <i class="fas fa-sign-out-alt nav-logo"></i>
                <span class="tooltiptext">Déconnexion</span>
            </a>
        </div>

    </nav>

    <div class="main-container">
        <div class="content-container">
            <h1 class="title-list">Liste des élèves</h1>

            <table>
                <thead>
                    <tr class="head">
                        <th>Nom</th>
                        <th>Prénom</th>
                        <th>Note Développement</th>
                        <th>Note Réseau</th>
                        <th>Note Base de données</th>
                        <th>Moyenne</th>
                        <th>Taux de ponctualité</th>
                    </tr>
                </thead>

                <tbody>
                {% for user in users %}
                    <tr class="body">
                        <td>{{ user.lastname }}</td>
                        <td>{{ user.firstname }}</td>
                        <td>{{ user.markDev }}</td>
                        <td>{{ user.markNetwork }}</td>
                        <td>{{ user.markBdd }}</td>
                        <td>{{ (user.markDev + user.markNetwork + user.markBdd)/3 }}</td>
                        <td>{{ user.markPunctuality }}%</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

        </div>
    </div>


{% endblock %}

DashboardApp/templates/profile/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Dashboard | Votre profil{% endblock %}

{% block body %}

    <div class="example-wrapper">
        <nav>
            <div class="nav-elements">
                <a class="nav-item home-icon tooltip" href="{{ path('dashboard') }}">
                    <i class="material-icons nav-logo ">home</i>
                    <span class="tooltiptext">Accueil</span>
                </a>

                <a class="nav-item list-icon tooltip" href="{{ path('list') }}">
                    <i class="material-icons nav-logo">list</i>
                    <span class="tooltiptext">Liste</span>
                </a>

                <a class="nav-item profil-icon tooltip active-profil" href="{{ path('profile') }}">
                    <i class="material-icons nav-logo">account_circle</i>
                    <span class="tooltiptext">Profil</span>
                </a>
            </div>
            <div class="logout-element">
                <a class="nav-item logout-icon tooltip" href="{{ path('logout') }}">
                    <i class="fas fa-sign-out-alt nav-logo"></i>
                    <span class="tooltiptext">Déconnexion</span>
                </a>
            </div>
        </nav>

        <div class="main-container">

            <div class="content-container">
                <div class="card">
                    <div class="card-banner">
                        <div class="card-profile">
                            <i class="fas fa-user-circle user-photo"></i>
                        </div>
                        <h3>Votre profil</h3>
                        <hr>

                        <div class="info1">
                            <div class="personnal-info">
                                <p class="tag-info">Nom :</p>
                                <p>{{ app.user.lastname }}</p>
                            </div>

                            <div class="personnal-info">
                                <p class="tag-info">Prénom :</p>
                                <p>{{ app.user.firstname }}</p>
                            </div>

                            <div class="personnal-info">
                                <p class="tag-info">Nom d'utilisateur :</p>
                                <p>{{ app.user.username }}</p>
                            </div>

                            <div class="personnal-info">
                                <p class="tag-info">Adresse email :</p>
                                <p>{{ app.user.email }}</p>
                            </div>
                        </div>


                        <h3>Statistiques générales</h3>
                        <div class="progress-bars">
                            <div class="personnal-stat">
                                <p>Développement</p>
                                <p>{{ app.user.markDev }}/20</p>
                            </div>
                            <div class="personnal-stat">
                                <p>Réseau</p>
                                <p>{{ app.user.markNetwork }}/20</p>
                            </div>
                            <div class="personnal-stat">
                                <p>Base de données</p>
                                <p>{{ app.user.markBdd }}/20</p>
                            </div>
                            <div class="personnal-stat">
                                <p>Ponctualité</p>
                                <p>{{ app.user.markPunctuality }}%</p>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>

    </div>

</div>
{% endblock %}

DashboardApp/templates/security/login.html.twig
{% extends 'base.html.twig' %}

{% block title %}Connectez-vous !{% endblock %}

{% block body %}

<div class="form-div">
    <!--<a href="{{ path('logout') }}">Se déconnecter</a>-->
    <h1>CONNECTEZ-VOUS</h1>

    <hr class="form-hr">

    <form class="form-login" action="{{ path('login') }}" method="post">

        <div class="input">
            <i class="fas fa-user"></i>
            <input title="Veuillez compléter ce champ avec le nom d'utilisateur." class="username" type="text" name="_username" value="{{ last_username }}" placeholder="Nom d'utilisateur" required>
        </div>

        <div class="input">
            <i class="fas fa-key"></i>
            <input title="Veuillez compléter ce champ avec le mot de passe." type="password" name="_password" placeholder="Mot de passe" required>
        </div>

        <div class="error-div">
            {% if error %}
                <span class="error">Identifiants incorrects.</span><br>
                <span class="error">Veuillez saisir un identifiant et un mot de passe valides.</span>
            {% endif %}
        </div>
        <button type="submit">Se connecter</button>

    </form>

    <div class="bottom-form">
        <p>Powered by</p>
        <a href="https://symfony.com/" target="_blank">
            <img src="../../assets/img/symfony.svg">
        </a>
    </div>
</div>
{% endblock %}